```{r}
library(ggplot2)
library(dplyr)
library(readr)
library(tidyr)
```

```{r}
df <- read_csv('../data/diabetes_012_health_indicators_BRFSS2015.csv')
```

### Outliers

gom nhóm nhãn hiếm cho Education.       
1: Less than high school.       
2: High School.     
3: College.     
4: College gradute. 

```{r}
df <- df %>%
  mutate(Education = case_when(
    Education %in% c(1,2,3) ~ 1,
    Education %in% c(4,5,6) ~ Education
  )) %>%
  mutate(Education = factor(Education, levels = c(1,4,5,6), labels = c(1,2,3,4)))

df$Education <- as.double(as.character(df$Education))
```

```{r}
ggplot(df, aes(x=as.factor(Education), fill=Education)) +
    geom_bar() +
    labs(title = "Education Distribution",
         x = "Education Level",
         y = "Count") +
    theme_minimal() 
```

Scale lại toàn bộ dữ liệu cho các biến định lượng để giảm ảnh hưởng của outliers trong quá trình kiểm định giả thuyết. 

```{r}
robust_scaler <- function(x) {
  Q1 <- quantile(x, 0.25) 
  Q3 <- quantile(x, 0.75) 
  IQR <- Q3 - Q1          
  median_x <- median(x)   

  scaled_x <- (x - median_x) / IQR
  return(scaled_x)
}

df1 <- df %>%
  mutate(BMI = robust_scaler(BMI)) %>%
  mutate(PhysHlth = robust_scaler(PhysHlth)) %>%
  mutate(MentHlth = robust_scaler(MentHlth))
```

```{r}
# plot the distribution of BMI, PhysHlth, and MentHlth
par(mfrow=c(3,1), bg='white')
hist(df1$MentHlth, breaks=31, col='green', main='MentHlth Histogram')
hist(df1$PhysHlth, breaks=31, col='blue', main='PhysHlth Histogram')
hist(df1$BMI, breaks=84, col='red', main='BMI Histogram')
```

```{r}
write.csv(df1, '../data/clean_outliers.csv', row.names=FALSE)
```

Drop duplicate rows và chia dữ liệu train test cho quá trình xây dựng mô hình 

```{r}
df2 <-  distinct(df)
set.seed(345)
train_index <- sample(1:nrow(df2), 0.7*nrow(df2))
train <- df2[train_index,]
test <- df2[-train_index,]
```

```{r}
print("Train data:")
print(with(train, table(Diabetes_012)))
print("Test data:")
print(with(test, table(Diabetes_012)))
```

```{r}
train_summary <- train %>%
    summarise(
        IQR_BMI = IQR(BMI),
        median_BMI = median(BMI),
        IQR_MentHlth = IQR(MentHlth),
        median_MentHlth = median(MentHlth),
        IQR_PhysHlth = IQR(PhysHlth),
        median_PhysHlth = median(PhysHlth)
    ) %>%
    pivot_longer(cols = everything(), names_to = "Metric", values_to = "Value") %>%
    separate(Metric, into = c("Statistic", "Variable"), sep = "_") %>%
    pivot_wider(names_from = Statistic, values_from = Value)

print(train_summary)
```

```{r}
write.csv(train_summary, file = "../data/scale_parameters.csv", row.names = FALSE)
```

```{r}
robust_scaler2 <- function(x, IQR, median) {
    scaled_x <- (x - median) / IQR
    return(scaled_x)
}
```

```{r}
variables <- c("BMI", "MentHlth", "PhysHlth")
for (var in variables) {
    median_value <- train_summary %>% filter(Variable == var) %>% pull(median)
    IQR_value <- train_summary %>% filter(Variable == var) %>% pull(IQR)
    train[[var]] <- robust_scaler2(train[[var]], IQR_value, median_value)
    test[[var]] <- robust_scaler2(test[[var]], IQR_value, median_value)
}
```

```{r}
par(mfrow=c(3,1), bg='white')
hist(train$MentHlth, breaks=31, col='green', main='MentHlth Histogram')
hist(train$PhysHlth, breaks=31, col='blue', main='PhysHlth Histogram')
hist(train$BMI, breaks=84, col='red', main='BMI Histogram')
```

```{r}
write.csv(train, '../data/train_set/train_base.csv', row.names=FALSE)
write.csv(test, '../data/testset.csv', row.names=FALSE)
```

### Imbalanced 

```{r}
train <- read.csv('../data/train_set/train_base.csv')
```

Under Sampling 

```{r}
under_sampling_3c <- function(data, name_class) {
    class_fact <- as.factor(data[, name_class])
    data_split <- split(data, class_fact)
    n_class <- sapply(data_split, FUN = nrow)
    n_minor <- min(n_class)
    
    new_data <- do.call(rbind, lapply(data_split, function(class_data) {
        id_sample <- sample(1:nrow(class_data), size = n_minor, replace = FALSE)
        class_data[id_sample, ]
    }))
    
    return(new_data)
}

```

```{r}
set.seed(345)
train_under <- under_sampling_3c(train, "Diabetes_012")
with(train_under, table(Diabetes_012))
```

```{r}
# save the under-sampled data to csv 
write.csv(train_under, '../data/train_set/train_under.csv', row.names=FALSE)
```

Over Sampling

```{r}
over_sampling_3c <- function(data, name_class) {
    class_fact <- as.factor(data[, name_class])
    data_split <- split(data, class_fact)
    n_class <- sapply(data_split, FUN = nrow)
    n_major <- max(n_class)
    
    new_data <- do.call(rbind, lapply(data_split, function(class_data) {
        id_sample <- sample(1:nrow(class_data), size = n_major, replace = TRUE)
        class_data[id_sample, ]
    }))
    
    return(new_data)
}
```

```{r}
set.seed(345)
train_over <- over_sampling_3c(train, "Diabetes_012")
with(train_over, table(Diabetes_012))
```

```{r}
write.csv(train_over, '../data/train_set/train_over.csv', row.names=FALSE)
```

Under + Over Sampling

```{r}
# kết hợp under sampling và over sampling cho 3 classes
combine_sampling_3c <- function(data, name_class) {
    class_fact <- as.factor(data[, name_class])
    data_split <- split(data, class_fact)
    n_class <- sapply(data_split, FUN = nrow)
    
    # xác định cỡ mẫu chung cho các class (avg)
    n_avg <- round(mean(n_class))

    new_data <- do.call(rbind, lapply(data_split, function(class_data) {
        n_class_data <- nrow(class_data)
        if (n_class_data < n_avg) {
            id_sample <- sample(1:n_class_data, size = n_avg - n_class_data, replace = TRUE)
            class_data <- rbind(class_data, class_data[id_sample, ])
        } else {
            id_sample <- sample(1:n_class_data, size = n_avg, replace = FALSE)
            class_data <- class_data[id_sample, ]
        }
        return(class_data)
    }))
    
    return(new_data)
}
```

```{r}
set.seed(345)
train_combine <- combine_sampling_3c(train, "Diabetes_012")
with(train_combine, table(Diabetes_012))
```

```{r}
write.csv(train_combine, '../data/train_set/train_combine.csv', row.names=FALSE)
```

SMOTE

```{r}
library(themis)
```

```{r}
train$Diabetes_012 <- as.factor(train$Diabetes_012)
set.seed(345)
train_smote <- smotenc(df= train, var = "Diabetes_012", k = 5, over_ratio = 1)
```

```{r}
with(train_smote, table(Diabetes_012))
```

```{r}
write.csv(train_smote, '../data/train_set/train_smote.csv', row.names=FALSE)
```